services:
  stats-server:
    ports:
      - "9090:9090"
    build: ./stat-service/stat-server
    container_name: stat-server
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats_user
      - SPRING_DATASOURCE_PASSWORD=stats_psw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=always

  stats-db:
    image: postgres:16.1
    container_name: ps-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_psw
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "stats", "-U", "stats_user"]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm_user
      - SPRING_DATASOURCE_PASSWORD=ewm_psw
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_psw
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "ewm", "-U", "ewm_user" ]
      timeout: 5s
      interval: 5s
      retries: 10
