services:
  stats-server:
    ports:
      - "9090:9090"
    build: ./stat-service/stat-server
    container_name: stat-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats_user
      - SPRING_DATASOURCE_PASSWORD=stats_psw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=always

  stats-db:
    image: postgres:16.1
    container_name: ps-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_psw

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    container_name: ps-ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_psw
